### ISSUE TITLE
Why are you stealing my code?

### ISSUE THREAD

**Issue by monkxy** [Pointless606/Blooket-hacks#1]

**Comment by Jude-Gideon** [comment]
Just learn how to make hacks rather than blatantly stealing code, especially considering when this breaks (which it already doesnt work) you don't know how to fix it without going to my profile and stealing my code.

**Comment by Jude-Gideon** [comment]
I can tell when you steal my code, the obfuscation is the exact same and the file size as well, as I said before, take this down, put my name and github at the top of your readme, or I will have this taken down.

**Comment by Pointless606** [comment]
sorry il stop but only if you teach me how to write blooket hacks because the stuff on youtube doesn't make sense to me

**Comment by Pointless606** [comment]
Deal?

**Comment by Jude-Gideon** [comment]
> sorry il stop but only if you teach me how to write blooket hacks because the stuff on youtube doesn't make sense to me

I'm not teaching you anything, you either stop stealing my work or I'm going to email github and get this taken down, learn to code something different then study the app, there are so many unobfuscated hacks out there, look at how they work. This is your last chance, take these down and stop stealing work.

**Comment by HelloBello234** [comment]
Bro imagine stealing blooket hacks 💀 whats even the goal of that

**Comment by Pointless606** [comment]
BYE :)

**Comment by monkxy** [comment]
Github has been emailed.

**Comment by Jude-Gideon** [comment]
Github has been emailed.

**Comment by Pointless606** [comment]
what will they do its deleted

**Comment by Pointless606** [comment]
sorry I was being rude

**Comment by monkxy** [comment]
Okay, that you for deleting the code, I will delete the email. Look in to other repos on GitHub some have unobfuscated Blooket hacks which you can learn from, just don't steal their work.

**Comment by Pointless606** [comment]
Ummm yeah I got one question how do I learn how to write blooket hacks with javascript I searched it up and nothing useful showed up...

**Comment by monkxy** [comment]
learn js and react then try and study repos on github with unobfuscated code.
